targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
      freezed:
        options:
          copy_with: true
          equal: true
          to_json: true
          from_json: true
