import 'package:freezed_annotation/freezed_annotation.dart';

import '../../../core/utils/formatters.dart';

part 'meal.freezed.dart';
part 'meal.g.dart';

/// Type of meal within a daily meal plan.
///
/// Used to categorize meals and display them in the appropriate sections
/// of the daily plan view.
enum MealType {
  /// Morning meal (typically 6-10 AM)
  breakfast,

  /// Midday meal (typically 11 AM - 2 PM)
  lunch,

  /// Evening meal (typically 5-8 PM)
  dinner,

  /// Optional snack between main meals
  snack,
}

/// Extension methods for MealType enum.
extension MealTypeExtension on MealType {
  /// User-friendly display name for the meal type.
  String get displayName {
    switch (this) {
      case MealType.breakfast:
        return 'Breakfast';
      case MealType.lunch:
        return 'Lunch';
      case MealType.dinner:
        return 'Dinner';
      case MealType.snack:
        return 'Snack';
    }
  }

  /// Icon emoji representing the meal type.
  String get icon {
    switch (this) {
      case MealType.breakfast:
        return '🌅';
      case MealType.lunch:
        return '🌤️';
      case MealType.dinner:
        return '🌙';
      case MealType.snack:
        return '🍎';
    }
  }

  /// Time range description for the meal type.
  String get timeDescription {
    switch (this) {
      case MealType.breakfast:
        return 'Morning';
      case MealType.lunch:
        return 'Midday';
      case MealType.dinner:
        return 'Evening';
      case MealType.snack:
        return 'Anytime';
    }
  }

  /// JSON string value for serialization.
  String get jsonValue => name;

  /// Parse MealType from JSON string value.
  static MealType? fromJsonValue(String value) {
    switch (value.toLowerCase()) {
      case 'breakfast':
        return MealType.breakfast;
      case 'lunch':
        return MealType.lunch;
      case 'dinner':
        return MealType.dinner;
      case 'snack':
        return MealType.snack;
      default:
        return null;
    }
  }
}

/// Represents a single meal in the nutrition plan.
///
/// This model stores all information about a meal including its name, nutritional
/// macros, ingredients, preparation instructions, and completion status. Meals are
/// generated by Gemini AI to respect the user's dietary restrictions and align
/// with their fitness goals.
///
/// Key Features:
/// - Immutable data structure via Freezed
/// - JSON serialization for Gemini API parsing and Firestore storage
/// - Complete nutritional information (calories, protein, carbs, fat)
/// - Ingredient list and preparation instructions
/// - Completion tracking for daily task management
/// - Meal type categorization for proper scheduling
///
/// Example:
/// ```dart
/// final meal = Meal(
///   id: 'meal_123',
///   name: 'Greek Yogurt Parfait',
///   type: MealType.breakfast,
///   calories: 350,
///   protein: 25,
///   carbs: 45,
///   fat: 8,
///   ingredients: [
///     '1 cup Greek yogurt',
///     '1/2 cup granola',
///     '1/2 cup mixed berries',
///     '1 tbsp honey'
///   ],
///   instructions: 'Layer yogurt, granola, and berries. Drizzle with honey.',
///   isComplete: false,
/// );
///
/// // Mark as complete
/// final completed = meal.copyWith(isComplete: true);
///
/// // Parse from Gemini JSON response
/// final fromJson = Meal.fromJson(jsonData);
/// ```
///
/// Generated files:
/// - `meal.freezed.dart` - Freezed generated code
/// - `meal.g.dart` - JSON serialization code
///
/// Run `flutter pub run build_runner build` to generate after changes.
@freezed
class Meal with _$Meal {
  /// Private constructor for adding custom methods.
  const Meal._();

  /// Creates a Meal with the specified properties.
  ///
  /// All fields except [instructions] and [isComplete] are required.
  /// The [isComplete] field defaults to false for new meals.
  ///
  /// Parameters:
  /// - [id]: Unique identifier for the meal
  /// - [name]: Display name of the meal
  /// - [type]: Meal type (breakfast, lunch, dinner, snack)
  /// - [calories]: Estimated total calories
  /// - [protein]: Grams of protein
  /// - [carbs]: Grams of carbohydrates
  /// - [fat]: Grams of fat
  /// - [ingredients]: List of ingredients with quantities
  /// - [instructions]: Optional preparation instructions
  /// - [isComplete]: Whether the user has consumed this meal
  const factory Meal({
    /// Unique identifier for the meal.
    ///
    /// Generated during plan creation, persists across modifications.
    required String id,

    /// Display name of the meal.
    ///
    /// Examples: "Greek Yogurt Parfait", "Grilled Chicken Salad",
    /// "Protein Smoothie"
    required String name,

    /// Type of meal for daily scheduling.
    ///
    /// Determines when this meal should be consumed and how it's
    /// displayed in the daily plan.
    required MealType type,

    /// Estimated total calories for the meal.
    ///
    /// Calculated by Gemini AI based on ingredients and portions.
    /// Used for daily calorie tracking aligned with fitness goals.
    required int calories,

    /// Grams of protein in the meal.
    ///
    /// Protein targets vary by goal:
    /// - Muscle gain: Higher protein (1.6-2.2g per kg bodyweight)
    /// - Weight loss: Moderate-high protein (1.2-1.6g per kg)
    /// - General fitness: Moderate protein (0.8-1.2g per kg)
    required int protein,

    /// Grams of carbohydrates in the meal.
    ///
    /// Carb targets vary by goal and activity level:
    /// - Endurance: Higher carbs for fuel
    /// - Weight loss: Lower carbs (may vary)
    /// - Muscle gain: Moderate-high carbs for energy
    required int carbs,

    /// Grams of fat in the meal.
    ///
    /// Healthy fats are essential for hormone production and satiety.
    /// Typically 20-35% of total daily calories.
    required int fat,

    /// List of ingredients with quantities.
    ///
    /// Each ingredient includes quantity and unit for shopping and prep.
    /// Examples:
    /// - "1 cup Greek yogurt"
    /// - "6 oz grilled chicken breast"
    /// - "2 tbsp olive oil"
    /// - "1/2 cup quinoa (cooked)"
    @Default([]) List<String> ingredients,

    /// Optional preparation instructions.
    ///
    /// Brief cooking or assembly instructions. Can be null for simple
    /// meals that don't require preparation steps.
    ///
    /// Examples:
    /// - "Grill chicken for 6-8 minutes per side. Toss salad and serve."
    /// - "Blend all ingredients until smooth."
    /// - "Layer ingredients in a bowl."
    String? instructions,

    /// Whether the user has consumed this meal today.
    ///
    /// Defaults to false. Set to true when user checks off the meal.
    /// Used to calculate daily completion percentage.
    @Default(false) bool isComplete,
  }) = _Meal;

  /// Creates a Meal from a JSON map.
  ///
  /// Used for deserializing from:
  /// - Gemini AI API responses
  /// - Firestore documents
  /// - Local Hive storage
  ///
  /// Example:
  /// ```dart
  /// final json = {
  ///   'id': 'meal_123',
  ///   'name': 'Protein Smoothie',
  ///   'type': 'breakfast',
  ///   'calories': 350,
  ///   'protein': 30,
  ///   'carbs': 40,
  ///   'fat': 8,
  ///   'ingredients': ['1 scoop protein powder', '1 banana', '1 cup almond milk'],
  ///   'isComplete': false,
  /// };
  /// final meal = Meal.fromJson(json);
  /// ```
  factory Meal.fromJson(Map<String, dynamic> json) => _$MealFromJson(json);

  /// Total macronutrients in grams (protein + carbs + fat).
  ///
  /// Useful for validating that macros match calorie estimate:
  /// - Protein: 4 calories per gram
  /// - Carbs: 4 calories per gram
  /// - Fat: 9 calories per gram
  int get totalMacros => protein + carbs + fat;

  /// Formatted display string for calories.
  ///
  /// Example: "350 cal"
  String get caloriesDisplay => Formatters.calories(calories);

  /// Formatted display string for protein.
  ///
  /// Example: "25g protein"
  String get proteinDisplay => Formatters.macros(protein, 'protein');

  /// Formatted display string for carbs.
  ///
  /// Example: "45g carbs"
  String get carbsDisplay => Formatters.macros(carbs, 'carbs');

  /// Formatted display string for fat.
  ///
  /// Example: "8g fat"
  String get fatDisplay => Formatters.macros(fat, 'fat');

  /// Complete macro summary string.
  ///
  /// Example: "350 cal • 25g protein • 45g carbs • 8g fat"
  String get macroSummary =>
      '$caloriesDisplay • $proteinDisplay • $carbsDisplay • $fatDisplay';

  /// Short macro summary for compact display.
  ///
  /// Example: "P: 25g | C: 45g | F: 8g"
  String get shortMacroSummary => 'P: ${protein}g | C: ${carbs}g | F: ${fat}g';

  /// Number of ingredients in the meal.
  ///
  /// Useful for displaying meal complexity.
  int get ingredientCount => ingredients.length;

  /// Whether this meal has preparation instructions.
  bool get hasInstructions =>
      instructions != null && instructions!.trim().isNotEmpty;

  /// Whether this is a simple meal (few ingredients, no cooking).
  ///
  /// Considers a meal simple if it has 5 or fewer ingredients.
  bool get isSimpleMeal => ingredientCount <= 5;

  /// Estimated preparation time category based on complexity.
  ///
  /// Returns a human-readable time estimate.
  String get estimatedPrepTime {
    if (!hasInstructions || ingredientCount <= 3) {
      return '< 5 min';
    } else if (ingredientCount <= 6) {
      return '10-15 min';
    } else {
      return '20-30 min';
    }
  }

  /// Meal display name with type.
  ///
  /// Example: "Greek Yogurt Parfait (Breakfast)"
  String get fullName => '$name (${type.displayName})';
}
