import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:fitgenie_app/features/plan_generation/domain/exercise.dart';

import '../../../core/utils/formatters.dart';

part 'workout.freezed.dart';
part 'workout.g.dart';

/// Type of workout session.
///
/// Categorizes workouts by their primary training focus, allowing the AI
/// to generate appropriate exercise selections and programming.
enum WorkoutType {
  /// Resistance training focused on building strength and muscle.
  ///
  /// Typically includes compound and isolation exercises with weights.
  strength,

  /// Cardiovascular training to improve aerobic capacity.
  ///
  /// Includes running, cycling, HIIT, or other heart-rate elevating activities.
  cardio,

  /// Stretching and mobility work to improve range of motion.
  ///
  /// Includes yoga, static stretching, and dynamic mobility drills.
  flexibility,

  /// Rest day with no structured workout.
  ///
  /// Active recovery like walking or light stretching is acceptable.
  rest,
}

/// Extension methods for WorkoutType enum.
extension WorkoutTypeExtension on WorkoutType {
  /// User-friendly display name for the workout type.
  String get displayName {
    switch (this) {
      case WorkoutType.strength:
        return 'Strength Training';
      case WorkoutType.cardio:
        return 'Cardio';
      case WorkoutType.flexibility:
        return 'Flexibility';
      case WorkoutType.rest:
        return 'Rest Day';
    }
  }

  /// Icon emoji representing the workout type.
  String get icon {
    switch (this) {
      case WorkoutType.strength:
        return '💪';
      case WorkoutType.cardio:
        return '🏃';
      case WorkoutType.flexibility:
        return '🧘';
      case WorkoutType.rest:
        return '😌';
    }
  }

  /// Brief description of the workout type.
  String get description {
    switch (this) {
      case WorkoutType.strength:
        return 'Build muscle and increase strength';
      case WorkoutType.cardio:
        return 'Improve cardiovascular endurance';
      case WorkoutType.flexibility:
        return 'Enhance mobility and flexibility';
      case WorkoutType.rest:
        return 'Recovery and regeneration';
    }
  }

  /// JSON string value for serialization.
  String get jsonValue => name;

  /// Parse WorkoutType from JSON string value.
  static WorkoutType? fromJsonValue(String value) {
    switch (value.toLowerCase()) {
      case 'strength':
        return WorkoutType.strength;
      case 'cardio':
        return WorkoutType.cardio;
      case 'flexibility':
        return WorkoutType.flexibility;
      case 'rest':
        return WorkoutType.rest;
      default:
        return null;
    }
  }

  /// Whether this workout type involves active exercise.
  bool get isActiveWorkout => this != WorkoutType.rest;
}

/// Represents a complete workout session.
///
/// This model aggregates multiple exercises into a structured workout session
/// with metadata like name, type, duration, and completion tracking. Workouts
/// are generated by Gemini AI to match the user's available equipment, fitness
/// level, and training goals.
///
/// Key Features:
/// - Immutable data structure via Freezed
/// - JSON serialization for Gemini API parsing and Firestore storage
/// - Ordered list of exercises with progression
/// - Type categorization (strength, cardio, flexibility, rest)
/// - Automatic completion tracking based on exercise completion
/// - Duration estimation for time management
///
/// Example:
/// ```dart
/// final workout = Workout(
///   id: 'workout_123',
///   name: 'Upper Body Strength',
///   type: WorkoutType.strength,
///   durationMinutes: 45,
///   exercises: [
///     Exercise(id: 'ex1', name: 'Push-ups', sets: 3, reps: '15', ...),
///     Exercise(id: 'ex2', name: 'Dumbbell Rows', sets: 3, reps: '10-12', ...),
///   ],
/// );
///
/// // Check completion
/// if (workout.isComplete) {
///   print('Workout completed!');
/// }
///
/// // Parse from Gemini JSON response
/// final fromJson = Workout.fromJson(jsonData);
/// ```
///
/// Generated files:
/// - `workout.freezed.dart` - Freezed generated code
/// - `workout.g.dart` - JSON serialization code
///
/// Run `flutter pub run build_runner build` to generate after changes.
@freezed
class Workout with _$Workout {
  /// Private constructor for adding custom methods.
  const Workout._();

  /// Creates a Workout with the specified properties.
  ///
  /// All fields are required except the exercises list defaults to empty.
  ///
  /// Parameters:
  /// - [id]: Unique identifier for the workout
  /// - [name]: Display name of the workout session
  /// - [type]: Type of workout (strength, cardio, flexibility, rest)
  /// - [durationMinutes]: Estimated total duration including rest
  /// - [exercises]: Ordered list of exercises in the workout
  const factory Workout({
    /// Unique identifier for the workout.
    ///
    /// Generated during plan creation, persists across modifications.
    required String id,

    /// Display name of the workout session.
    ///
    /// Examples: "Upper Body Strength", "HIIT Cardio", "Full Body Circuit",
    /// "Lower Body Power"
    required String name,

    /// Type of workout session.
    ///
    /// Determines the focus and structure of the workout:
    /// - Strength: Resistance training with weights or bodyweight
    /// - Cardio: Heart-rate elevating aerobic exercise
    /// - Flexibility: Stretching and mobility work
    /// - Rest: Recovery day with no structured workout
    required WorkoutType type,

    /// Estimated total duration in minutes.
    ///
    /// Includes:
    /// - Warm-up time (5-10 minutes)
    /// - Exercise working time
    /// - Rest periods between sets
    /// - Cool-down time (5-10 minutes)
    ///
    /// Used for scheduling and time management.
    required int durationMinutes,

    /// Ordered list of exercises in the workout.
    ///
    /// Exercises are performed in the order listed. Empty list for rest days.
    /// Typical workout contains 4-8 exercises for strength training,
    /// 3-5 intervals for cardio, or 8-12 stretches for flexibility.
    @Default([]) List<Exercise> exercises,
  }) = _Workout;

  /// Creates a Workout from a JSON map.
  ///
  /// Used for deserializing from:
  /// - Gemini AI API responses
  /// - Firestore documents
  /// - Local Hive storage
  ///
  /// Example:
  /// ```dart
  /// final json = {
  ///   'id': 'workout_123',
  ///   'name': 'Upper Body Strength',
  ///   'type': 'strength',
  ///   'durationMinutes': 45,
  ///   'exercises': [
  ///     {'id': 'ex1', 'name': 'Push-ups', 'sets': 3, 'reps': '15', ...},
  ///     {'id': 'ex2', 'name': 'Rows', 'sets': 3, 'reps': '10', ...},
  ///   ],
  /// };
  /// final workout = Workout.fromJson(json);
  /// ```
  factory Workout.fromJson(Map<String, dynamic> json) =>
      _$WorkoutFromJson(json);

  /// Whether all exercises in the workout have been completed.
  ///
  /// Returns true if:
  /// - All exercises have isComplete = true, OR
  /// - Workout is a rest day (no exercises)
  ///
  /// Returns false if any exercise is incomplete.
  bool get isComplete {
    if (exercises.isEmpty) {
      // Rest day or empty workout is considered complete
      return true;
    }
    return exercises.every((exercise) => exercise.isComplete);
  }

  /// Percentage of exercises completed (0-100).
  ///
  /// Calculates: (completed exercises / total exercises) * 100
  /// Returns 100 for rest days or empty workouts.
  double get completionPercentage {
    if (exercises.isEmpty) {
      return 100.0;
    }
    final completedCount = exercises
        .where((exercise) => exercise.isComplete)
        .length;
    return (completedCount / exercises.length) * 100;
  }

  /// Number of exercises completed.
  int get completedExerciseCount =>
      exercises.where((exercise) => exercise.isComplete).length;

  /// Total number of exercises in the workout.
  int get totalExerciseCount => exercises.length;

  /// Formatted display string for duration.
  ///
  /// Examples:
  /// - "45 mins"
  /// - "30 mins"
  /// - "1 hour"
  String get durationDisplay => Formatters.duration(durationMinutes);

  /// Formatted display string for exercise count.
  ///
  /// Examples:
  /// - "6 exercises"
  /// - "1 exercise"
  /// - "0 exercises" (rest day)
  String get exerciseCountDisplay =>
      Formatters.count(totalExerciseCount, 'exercise');

  /// Formatted progress string.
  ///
  /// Examples:
  /// - "3/6 exercises"
  /// - "0/5 exercises"
  /// - "Complete" (when all done)
  String get progressDisplay {
    if (isComplete) {
      return 'Complete';
    }
    return '${Formatters.completionRatio(completedExerciseCount, totalExerciseCount)} ${Formatters.count(totalExerciseCount, 'exercise')}';
  }

  /// Brief summary of the workout.
  ///
  /// Example: "Upper Body Strength • 45 min • 6 exercises"
  String get summary => '$name • $durationDisplay • $exerciseCountDisplay';

  /// Whether this is a rest day workout.
  bool get isRestDay => type == WorkoutType.rest || exercises.isEmpty;

  /// List of all unique equipment required for this workout.
  ///
  /// Aggregates equipment from all exercises, removing duplicates.
  /// Returns empty list for rest days.
  List<String> get requiredEquipment {
    if (exercises.isEmpty) {
      return [];
    }

    final equipmentSet = <String>{};
    for (final exercise in exercises) {
      equipmentSet.addAll(exercise.equipmentRequired);
    }

    // Remove 'bodyweight' if other equipment exists
    if (equipmentSet.length > 1) {
      equipmentSet.remove('bodyweight');
    }

    return equipmentSet.toList()..sort();
  }

  /// Formatted display string for required equipment.
  ///
  /// Examples:
  /// - "Dumbbells, Bench"
  /// - "Bodyweight only"
  /// - "No equipment" (rest day)
  String get equipmentDisplay {
    if (isRestDay) {
      return 'No equipment';
    }

    final equipment = requiredEquipment;
    if (equipment.isEmpty ||
        (equipment.length == 1 && equipment.first == 'bodyweight')) {
      return 'Bodyweight only';
    }

    // Capitalize each equipment item
    final capitalized = equipment
        .map(
          (e) => e
              .split(' ')
              .map((word) => word[0].toUpperCase() + word.substring(1))
              .join(' '),
        )
        .toList();

    return capitalized.join(', ');
  }

  /// Whether this workout requires any equipment.
  bool get requiresEquipment {
    final equipment = requiredEquipment;
    return equipment.isNotEmpty &&
        !(equipment.length == 1 && equipment.first == 'bodyweight');
  }

  /// Total number of sets across all exercises.
  ///
  /// Useful for workout volume tracking.
  int get totalSets {
    return exercises.fold(0, (sum, exercise) => sum + exercise.sets);
  }

  /// Workout intensity level based on type and volume.
  ///
  /// Returns: 'Light', 'Moderate', or 'High'
  String get intensityLevel {
    if (isRestDay) {
      return 'Rest';
    }

    // Simple heuristic based on duration and exercise count
    if (type == WorkoutType.cardio) {
      return durationMinutes >= 30 ? 'High' : 'Moderate';
    }

    // For strength training, consider volume
    if (totalSets >= 15) {
      return 'High';
    } else if (totalSets >= 10) {
      return 'Moderate';
    } else {
      return 'Light';
    }
  }
}
