import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive/hive.dart';
import 'package:fitgenie_app/core/constants/dietary_options.dart';
import 'package:fitgenie_app/core/utils/formatters.dart';

part 'user_profile.freezed.dart';
part 'user_profile.g.dart';

/// User's fitness goal selection.
///
/// Determines the type of training program and meal plan generated by the AI.
@HiveType(typeId: 10)
enum FitnessGoal {
  /// Build muscle mass and strength
  @HiveField(0)
  muscleGain,

  /// Lose body fat and weight
  @HiveField(1)
  weightLoss,

  /// Improve overall fitness and health
  @HiveField(2)
  generalFitness,

  /// Improve cardiovascular endurance and stamina
  @HiveField(3)
  endurance,
}

/// Extension methods for FitnessGoal enum.
extension FitnessGoalExtension on FitnessGoal {
  /// User-friendly display name.
  String get displayName {
    switch (this) {
      case FitnessGoal.muscleGain:
        return 'Build Muscle';
      case FitnessGoal.weightLoss:
        return 'Lose Weight';
      case FitnessGoal.generalFitness:
        return 'General Fitness';
      case FitnessGoal.endurance:
        return 'Improve Endurance';
    }
  }

  /// Short description of the goal.
  String get description {
    switch (this) {
      case FitnessGoal.muscleGain:
        return 'Build muscle mass and strength';
      case FitnessGoal.weightLoss:
        return 'Lose body fat and weight';
      case FitnessGoal.generalFitness:
        return 'Improve overall health and fitness';
      case FitnessGoal.endurance:
        return 'Improve cardiovascular endurance';
    }
  }

  /// Icon emoji representing the goal.
  String get icon {
    switch (this) {
      case FitnessGoal.muscleGain:
        return '💪';
      case FitnessGoal.weightLoss:
        return '⚖️';
      case FitnessGoal.generalFitness:
        return '🏃';
      case FitnessGoal.endurance:
        return '🚴';
    }
  }

  /// Firestore-compatible string value.
  String get firestoreValue {
    switch (this) {
      case FitnessGoal.muscleGain:
        return 'muscle_gain';
      case FitnessGoal.weightLoss:
        return 'weight_loss';
      case FitnessGoal.generalFitness:
        return 'general_fitness';
      case FitnessGoal.endurance:
        return 'endurance';
    }
  }

  /// AI prompt-friendly string value.
  String get promptValue {
    switch (this) {
      case FitnessGoal.muscleGain:
        return 'build muscle mass and increase strength';
      case FitnessGoal.weightLoss:
        return 'lose weight and reduce body fat';
      case FitnessGoal.generalFitness:
        return 'improve overall fitness and maintain health';
      case FitnessGoal.endurance:
        return 'improve cardiovascular endurance and stamina';
    }
  }

  /// Parse from Firestore string value.
  static FitnessGoal? fromFirestoreValue(String value) {
    switch (value) {
      case 'muscle_gain':
        return FitnessGoal.muscleGain;
      case 'weight_loss':
        return FitnessGoal.weightLoss;
      case 'general_fitness':
        return FitnessGoal.generalFitness;
      case 'endurance':
        return FitnessGoal.endurance;
      default:
        return null;
    }
  }
}

/// Type of equipment available to the user.
///
/// Determines which exercises can be included in workout plans.
@HiveType(typeId: 11)
enum EquipmentType {
  /// Full commercial gym with all equipment
  @HiveField(0)
  fullGym,

  /// Home gym with selected equipment
  @HiveField(1)
  homeGym,

  /// Bodyweight exercises only
  @HiveField(2)
  bodyweight,

  /// Mixed/custom combination
  @HiveField(3)
  mixed,
}

/// Extension methods for EquipmentType enum.
extension EquipmentTypeExtension on EquipmentType {
  /// User-friendly display name.
  String get displayName {
    switch (this) {
      case EquipmentType.fullGym:
        return 'Full Gym Access';
      case EquipmentType.homeGym:
        return 'Home Gym';
      case EquipmentType.bodyweight:
        return 'Bodyweight Only';
      case EquipmentType.mixed:
        return 'Mixed/Custom';
    }
  }

  /// Description of the equipment type.
  String get description {
    switch (this) {
      case EquipmentType.fullGym:
        return 'Access to a commercial gym with all equipment';
      case EquipmentType.homeGym:
        return 'Home gym with specific equipment';
      case EquipmentType.bodyweight:
        return 'No equipment - bodyweight exercises only';
      case EquipmentType.mixed:
        return 'Combination of gym and home workouts';
    }
  }

  /// Icon emoji representing the equipment type.
  String get icon {
    switch (this) {
      case EquipmentType.fullGym:
        return '🏋️';
      case EquipmentType.homeGym:
        return '🏠';
      case EquipmentType.bodyweight:
        return '🤸';
      case EquipmentType.mixed:
        return '🔀';
    }
  }

  /// Firestore-compatible string value.
  String get firestoreValue {
    switch (this) {
      case EquipmentType.fullGym:
        return 'full_gym';
      case EquipmentType.homeGym:
        return 'home_gym';
      case EquipmentType.bodyweight:
        return 'bodyweight';
      case EquipmentType.mixed:
        return 'mixed';
    }
  }

  /// Whether this equipment type requires detailed equipment list.
  bool get requiresDetails =>
      this == EquipmentType.homeGym || this == EquipmentType.mixed;

  /// Parse from Firestore string value.
  static EquipmentType? fromFirestoreValue(String value) {
    switch (value) {
      case 'full_gym':
        return EquipmentType.fullGym;
      case 'home_gym':
        return EquipmentType.homeGym;
      case 'bodyweight':
        return EquipmentType.bodyweight;
      case 'mixed':
        return EquipmentType.mixed;
      default:
        return null;
    }
  }
}

/// Weight measurement unit.
@HiveType(typeId: 12)
enum WeightUnit {
  /// Kilograms
  @HiveField(0)
  kg,

  /// Pounds
  @HiveField(1)
  lbs,
}

/// Extension methods for WeightUnit enum.
extension WeightUnitExtension on WeightUnit {
  /// Display string for the unit.
  String get displayName {
    switch (this) {
      case WeightUnit.kg:
        return 'kg';
      case WeightUnit.lbs:
        return 'lbs';
    }
  }

  /// Firestore-compatible string value.
  String get firestoreValue => displayName;

  /// Parse from Firestore string value.
  static WeightUnit? fromFirestoreValue(String value) {
    switch (value) {
      case 'kg':
        return WeightUnit.kg;
      case 'lbs':
        return WeightUnit.lbs;
      default:
        return null;
    }
  }
}

/// Height measurement unit.
@HiveType(typeId: 13)
enum HeightUnit {
  /// Centimeters
  @HiveField(0)
  cm,

  /// Feet and inches
  @HiveField(1)
  ftIn,
}

/// Extension methods for HeightUnit enum.
extension HeightUnitExtension on HeightUnit {
  /// Display string for the unit.
  String get displayName {
    switch (this) {
      case HeightUnit.cm:
        return 'cm';
      case HeightUnit.ftIn:
        return 'ft/in';
    }
  }

  /// Firestore-compatible string value.
  String get firestoreValue {
    switch (this) {
      case HeightUnit.cm:
        return 'cm';
      case HeightUnit.ftIn:
        return 'ft-in';
    }
  }

  /// Parse from Firestore string value.
  static HeightUnit? fromFirestoreValue(String value) {
    switch (value) {
      case 'cm':
        return HeightUnit.cm;
      case 'ft-in':
        return HeightUnit.ftIn;
      default:
        return null;
    }
  }
}

/// Complete user profile data collected during onboarding.
///
/// This model represents all information needed to generate personalized
/// fitness and nutrition plans via the Gemini AI. It includes biometric data,
/// fitness goals, available equipment, and dietary preferences.
///
/// The profile is persisted both locally (Hive) for offline access and
/// remotely (Firestore) for cross-device sync and AI plan generation.
///
/// Usage:
/// ```dart
/// final profile = UserProfile(
///   age: 28,
///   weight: 75.0,
///   weightUnit: WeightUnit.kg,
///   height: 180.0,
///   heightUnit: HeightUnit.cm,
///   goal: FitnessGoal.muscleGain,
///   equipment: EquipmentType.homeGym,
///   equipmentDetails: ['dumbbells', 'pull-up bar', 'yoga mat'],
///   dietaryRestrictions: [DietaryRestriction.vegetarian],
///   dietaryNotes: 'Nut allergy',
/// );
///
/// // Convert to Firestore
/// final firestoreData = profile.toFirestore();
///
/// // Convert from Firestore
/// final fromFirestore = UserProfile.fromFirestore(firestoreData);
/// ```
///
/// Generated files:
/// - `user_profile.freezed.dart` - Freezed generated code
/// - `user_profile.g.dart` - JSON and Hive serialization code
///
/// Run `flutter pub run build_runner build` to generate after changes.
@freezed
@HiveType(typeId: 1, adapterName: 'UserProfileAdapter')
class UserProfile with _$UserProfile {
  const UserProfile._();

  const factory UserProfile({
    /// User's age in years (13-100)
    @HiveField(0) required int age,

    /// User's weight value
    @HiveField(1) required double weight,

    /// Unit for weight measurement
    @HiveField(2) required WeightUnit weightUnit,

    /// User's height value
    /// - For cm: direct value (e.g., 180.0)
    /// - For ft/in: stored as total inches (e.g., 71.0 for 5'11")
    @HiveField(3) required double height,

    /// Unit for height measurement
    @HiveField(4) required HeightUnit heightUnit,

    /// Primary fitness goal
    @HiveField(5) required FitnessGoal goal,

    /// Type of equipment available
    @HiveField(6) required EquipmentType equipment,

    /// Specific equipment items available (for homeGym/mixed)
    ///
    /// Examples: 'dumbbells', 'barbell', 'pull-up bar', 'resistance bands',
    /// 'kettlebells', 'yoga mat', 'bench', 'treadmill'
    @HiveField(7) @Default([]) List<String> equipmentDetails,

    /// List of dietary restrictions
    @HiveField(8) required List<DietaryRestriction> dietaryRestrictions,

    /// Additional dietary notes (allergies, preferences, timing)
    @HiveField(9) String? dietaryNotes,
  }) = _UserProfile;

  /// Creates a UserProfile from JSON map (Firestore document).
  ///
  /// Handles enum deserialization from Firestore string values.
  factory UserProfile.fromJson(Map<String, dynamic> json) =>
      _$UserProfileFromJson(json);

  /// Creates a UserProfile from Firestore document data.
  ///
  /// This factory handles the conversion from Firestore's string-based
  /// enum storage to Dart enums, with proper error handling for invalid data.
  factory UserProfile.fromFirestore(Map<String, dynamic> data) {
    return UserProfile(
      age: data['age'] as int,
      weight: (data['weight'] as num).toDouble(),
      weightUnit:
          WeightUnitExtension.fromFirestoreValue(
            data['weightUnit'] as String,
          ) ??
          WeightUnit.kg,
      height: (data['height'] as num).toDouble(),
      heightUnit:
          HeightUnitExtension.fromFirestoreValue(
            data['heightUnit'] as String,
          ) ??
          HeightUnit.cm,
      goal:
          FitnessGoalExtension.fromFirestoreValue(data['goal'] as String) ??
          FitnessGoal.generalFitness,
      equipment:
          EquipmentTypeExtension.fromFirestoreValue(
            data['equipment'] as String,
          ) ??
          EquipmentType.bodyweight,
      equipmentDetails:
          (data['equipmentDetails'] as List<dynamic>?)
              ?.map((e) => e as String)
              .toList() ??
          [],
      dietaryRestrictions: DietaryRestrictionHelper.fromFirestoreList(
        (data['dietaryRestrictions'] as List<dynamic>?)
                ?.map((e) => e as String)
                .toList() ??
            [],
      ),
      dietaryNotes: data['dietaryNotes'] as String?,
    );
  }

  /// Converts UserProfile to Firestore-compatible map.
  ///
  /// Uses string representations of enums for Firestore storage.
  Map<String, dynamic> toFirestore() {
    return {
      'age': age,
      'weight': weight,
      'weightUnit': weightUnit.firestoreValue,
      'height': height,
      'heightUnit': heightUnit.firestoreValue,
      'goal': goal.firestoreValue,
      'equipment': equipment.firestoreValue,
      'equipmentDetails': equipmentDetails,
      'dietaryRestrictions': DietaryRestrictionHelper.toFirestoreList(
        dietaryRestrictions,
      ),
      if (dietaryNotes != null) 'dietaryNotes': dietaryNotes,
    };
  }

  /// Builds a formatted string for AI prompt generation.
  ///
  /// This creates a human-readable summary of the user's profile that will
  /// be included in the Gemini API prompt for plan generation.
  ///
  /// Example output:
  /// ```
  /// Age: 28 years old
  /// Weight: 75 kg
  /// Height: 180 cm
  /// Goal: build muscle mass and increase strength
  /// Equipment: Home Gym (dumbbells, pull-up bar, yoga mat)
  /// Dietary: vegetarian (no meat, fish, or poultry), nut-free (no tree nuts or peanuts)
  /// Additional notes: Nut allergy
  /// ```
  String toPromptContext() {
    final buffer = StringBuffer();

    buffer.writeln('Age: $age years old');
    buffer.writeln(
      'Weight: ${Formatters.weight(weight, weightUnit.displayName)}',
    );
    buffer.writeln(
      'Height: ${Formatters.height(height, heightUnit.firestoreValue)}',
    );
    buffer.writeln('Goal: ${goal.promptValue}');

    // Equipment details
    buffer.write('Equipment: ${equipment.displayName}');
    if (equipmentDetails.isNotEmpty) {
      buffer.write(' (${Formatters.list(equipmentDetails)})');
    }
    buffer.writeln();

    // Dietary restrictions
    buffer.write('Dietary: ');
    buffer.writeln(
      DietaryRestrictionHelper.formatForPrompt(dietaryRestrictions),
    );

    // Additional notes
    if (dietaryNotes != null && dietaryNotes!.isNotEmpty) {
      buffer.writeln('Additional notes: $dietaryNotes');
    }

    return buffer.toString();
  }

  /// Formatted weight display string.
  ///
  /// Example: "75 kg" or "165 lbs"
  String get weightDisplay {
    return Formatters.weight(weight, weightUnit.displayName);
  }

  /// Formatted height display string.
  ///
  /// Example: "180 cm" or "5'11""
  String get heightDisplay {
    return Formatters.height(height, heightUnit.firestoreValue);
  }

  /// Formatted equipment display string.
  ///
  /// Example: "Home Gym" or "Home Gym: dumbbells, pull-up bar"
  String get equipmentDisplay {
    if (equipmentDetails.isEmpty) {
      return equipment.displayName;
    }
    return '${equipment.displayName}: ${Formatters.list(equipmentDetails)}';
  }

  /// Formatted dietary restrictions display string.
  ///
  /// Example: "Vegetarian, Nut-Free" or "No Restrictions"
  String get dietaryDisplay {
    return DietaryRestrictionHelper.formatMultiple(dietaryRestrictions);
  }

  /// Whether the user has specified detailed equipment.
  bool get hasEquipmentDetails => equipmentDetails.isNotEmpty;

  /// Whether the user has any dietary restrictions.
  bool get hasDietaryRestrictions =>
      dietaryRestrictions.isNotEmpty && !dietaryRestrictions.first.isNone;

  /// Whether the user has additional dietary notes.
  bool get hasDietaryNotes =>
      dietaryNotes != null && dietaryNotes!.trim().isNotEmpty;
}
