import 'package:fitgenie_app/core/constants/app_colors.dart';
import 'package:flutter/material.dart';

/// Material 3 ColorScheme generation for FitGenie app.
///
/// This class generates harmonious color schemes from the brand seed color
/// using Material Design 3's color system. It provides both light and dark
/// mode color schemes with custom overrides for semantic colors.
///
/// Color Generation Strategy:
/// - Base colors generated via ColorScheme.fromSeed() using brand primary
/// - Custom overrides for error, success, and semantic states
/// - WCAG 2.1 AA contrast ratios maintained for accessibility
///
/// Usage:
/// ```dart
/// final lightColors = AppColorScheme.light;
/// final darkColors = AppColorScheme.dark;
/// ```
class AppColorScheme {
  AppColorScheme._(); // Private constructor to prevent instantiation

  // ==========================================================================
  // LIGHT MODE COLOR SCHEME
  // ==========================================================================

  /// Light mode ColorScheme generated from brand seed color.
  ///
  /// Uses Material 3's tonal palette system to create a harmonious color
  /// scheme that adapts the primary color across all UI elements.
  ///
  /// Key characteristics:
  /// - High contrast for readability
  /// - Warm primary (energetic coral #F97316)
  /// - Cool secondary (cyan) for contrast
  /// - Success states use lime green
  static ColorScheme get light {
    return ColorScheme.fromSeed(
      seedColor: AppColors.primarySeed,
      brightness: Brightness.light,
    ).copyWith(
      // Primary colors (already generated from seed, but can override)
      primary: AppColors.primaryLight,
      onPrimary: AppColors.onPrimary,

      // Secondary colors
      secondary: AppColors.secondaryLight,
      onSecondary: AppColors.onSecondary,

      // Tertiary colors (success states)
      tertiary: AppColors.tertiaryLight,
      onTertiary: AppColors.onTertiary,

      // Error colors
      error: AppColors.errorLight,
      onError: AppColors.onError,

      // Surface colors
      surface: AppColors.surfaceLight,
      onSurface: AppColors.onSurfaceLight,

      // Container variants - generated by Material 3 but can be customized
      surfaceContainerLowest: AppColors.surfaceLight,
      surfaceContainerLow: const Color(0xFFF5F5F4),
      surfaceContainer: const Color(0xFFE7E5E4),
      surfaceContainerHigh: const Color(0xFFD6D3D1),
      surfaceContainerHighest: const Color(0xFFA8A29E),

      // Outline colors for borders and dividers
      outline: AppColors.borderLight,
      outlineVariant: AppColors.dividerLight,

      // Shadow and scrim
      shadow: AppColors.shadowLight,
      scrim: Colors.black,

      // Inverse colors for snackbars and tooltips
      inverseSurface: AppColors.surfaceDark,
      onInverseSurface: AppColors.onSurfaceDark,
      inversePrimary: AppColors.primaryDark,

      // Surface tint for elevated surfaces
      surfaceTint: AppColors.primaryLight,
    );
  }

  // ==========================================================================
  // DARK MODE COLOR SCHEME
  // ==========================================================================

  /// Dark mode ColorScheme generated from brand seed color.
  ///
  /// Uses slightly lighter primary color for better visibility on dark
  /// backgrounds. Maintains brand identity while optimizing for low-light
  /// viewing conditions.
  ///
  /// Key characteristics:
  /// - Reduced contrast to prevent eye strain
  /// - Lighter primary (#FB923C) for visibility
  /// - Darker surface colors
  /// - Preserved semantic color meanings
  static ColorScheme get dark {
    return ColorScheme.fromSeed(
      seedColor: AppColors.primarySeed,
      brightness: Brightness.dark,
    ).copyWith(
      // Primary colors - slightly lighter for dark mode visibility
      primary: AppColors.primaryDark,
      onPrimary: AppColors.onPrimaryDark,

      // Secondary colors
      secondary: AppColors.secondaryDark,
      onSecondary: AppColors.onSecondary,

      // Tertiary colors (success states)
      tertiary: AppColors.tertiaryDark,
      onTertiary: AppColors.onTertiary,

      // Error colors
      error: AppColors.errorDark,
      onError: AppColors.onError,

      // Surface colors
      surface: AppColors.surfaceDark,
      onSurface: AppColors.onSurfaceDark,

      // Container variants - darker shades for dark mode
      surfaceContainerLowest: const Color(0xFF0C0A09),
      surfaceContainerLow: const Color(0xFF1C1917),
      surfaceContainer: const Color(0xFF292524),
      surfaceContainerHigh: const Color(0xFF44403C),
      surfaceContainerHighest: const Color(0xFF57534E),

      // Outline colors for borders and dividers
      outline: AppColors.borderDark,
      outlineVariant: AppColors.dividerDark,

      // Shadow and scrim
      shadow: AppColors.shadowDark,
      scrim: Colors.black,

      // Inverse colors for snackbars and tooltips
      inverseSurface: AppColors.surfaceLight,
      onInverseSurface: AppColors.onSurfaceLight,
      inversePrimary: AppColors.primaryLight,

      // Surface tint for elevated surfaces
      surfaceTint: AppColors.primaryDark,
    );
  }

  // ==========================================================================
  // SEMANTIC COLOR HELPERS
  // ==========================================================================

  /// Returns the success color for the given brightness.
  ///
  /// Used for completion states, positive feedback, and success messages.
  ///
  /// Example:
  /// ```dart
  /// final successColor = AppColorScheme.success(Brightness.light);
  /// ```
  static Color success(Brightness brightness) {
    return brightness == Brightness.light
        ? AppColors.success
        : AppColors.success;
  }

  /// Returns the warning color for the given brightness.
  ///
  /// Used for cautionary messages and alerts that require attention.
  ///
  /// Example:
  /// ```dart
  /// final warningColor = AppColorScheme.warning(Brightness.light);
  /// ```
  static Color warning(Brightness brightness) {
    return brightness == Brightness.light
        ? AppColors.warning
        : AppColors.warning;
  }

  /// Returns the info color for the given brightness.
  ///
  /// Used for informational messages and neutral notifications.
  ///
  /// Example:
  /// ```dart
  /// final infoColor = AppColorScheme.info(Brightness.light);
  /// ```
  static Color info(Brightness brightness) {
    return brightness == Brightness.light ? AppColors.info : AppColors.info;
  }
}
